services:
  frontend-vue:
    build:
      context: .
      dockerfile: config/docker/vue/Dockerfile
    command: npm run serve
    ports:
      - "80:8080"
    volumes:
      - ./frontend:/app
      - node_cache:/app/node_modules

volumes:
  node_cache:
